client_config_backend: file
client_config:
    client_id: 750422302885-lviq27rkldpl1acivst5p8pcbha4uoh2.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive